### ISSUE TITLE
Build fails with error "addWatchFile is not a function". Same behavior occurs on my machine and on Netlify

### ISSUE THREAD

**Issue by manach** [shaunchander/astro-pwa-starter#4]
I cloned the project and encountered the above error when I ran "npm run dev". So I tried the "deploy to Netlify" button from the Astro themes site and got the same error. Here is the detailed error message from the Netlify failed build:

```
at Object.astro:config:setup (/opt/build/repo/node_modules/@astrojs/tailwind/dist/index.js:100:11)

at async withTakingALongTimeMsg (file:///opt/build/repo/node_modules/astro/dist/integrations/index.js:13:18)

at async runHookConfigSetup (file:///opt/build/repo/node_modules/astro/dist/integrations/index.js:62:7)

at async AstroBuilder.setup (file:///opt/build/repo/node_modules/astro/dist/core/build/index.js:41:21)

at async AstroBuilder.run (file:///opt/build/repo/node_modules/astro/dist/core/build/index.js:125:23)

at async build (file:///opt/build/repo/node_modules/astro/dist/core/build/index.js:22:3)

at async runCommand (file:///opt/build/repo/node_modules/astro/dist/cli/index.js:190:14)

at async cli (file:///opt/build/repo/node_modules/astro/dist/cli/index.js:207:5)
```

Thanks for all your hard work; I'm new to Astro and just having this structure to work with is really helpful.

**Comment by yacosta738** [comment]
same issue here 

![bitmoji](https://sdk.bitmoji.com/render/panel/4a737c47-e262-44e8-b96e-66d11bb30cab-db1ffc10-9e7f-4bea-a043-e744f59d5043-v1.png?transparent=1&palette=1&width=246)

**Comment by shaunchander** [comment]
Hey @manach @yacosta738, thanks for checking out the starter! I'll take a closer look at this tonight. 

Does building and running the starter work locally for both of you?
